version: "2"
services:
	www:
		build:.
		ports:
			- "8001:80"
		volumes:
			- ./www:var/www/html
		links:
			- db
		networks:
			- default
	db:
		image: mysql
		ports:
			- "3306:3306"
		enviroment:
			MYSQL_DATABASE: myDb
			MYSQL_USER: user
			MYSQL_PASSWORD: test
			MYSQL_ROOT_PASSWORD: test
		volumes:
			- ./dump:/docker-entrypoint-initdb.db
			- persistent:/var/lib/mysql
		networks:
			- default
	phpmyadmin:
		image: phpmyadmin/phpmyadmin
		links: 
			- db:db
		ports: 
			- 8000:80
		enviroment:
			MYSQL_USER: user
			MYSQL_PASSWORD: test
			MYSQL_ROOT_PASSWORD: test
	
	volumes:
		persistent:
